# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='_equipment_alternatives_+', to='rcps.Equipment'),
        ),
    ]
