# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0003_remove_ingredientalternative_original_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientalternative',
            name='original_ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rcps.Ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_rating',
            field=models.FloatField(default=0),
        ),
    ]
