# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0004_auto_20161211_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientalternative',
            name='original_ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientalternative',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredientreplacement',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcps.IngredientAlternative'),
        ),
        migrations.AddField(
            model_name='ingredientreplacement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcps.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientreplacement',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcps.Recipe'),
        ),
    ]
