# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0005_auto_20161211_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientreplacement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientreplacement',
            name='ingredient_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rcps.Consist'),
            preserve_default=False,
        ),
    ]
