# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0007_remove_ingredientreplacement_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientalternative',
            name='alternative_quality',
        ),
        migrations.AddField(
            model_name='ingredientreplacement',
            name='alternative_quality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
