# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcps', '0008_auto_20161212_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_stars',
            field=models.IntegerField(null=True),
        ),
    ]
